# Accept the BASE_IMAGE_TAG argument
ARG BASE_IMAGE_TAG=latest-amd64

# Use codenap fastdds image with the argument to dynamically select the base image
FROM <...>/fastdds-docker:$BASE_IMAGE_TAG

RUN echo "deb [trusted=yes] https://download.eclipse.org/zenoh/debian-repo/ /" | tee -a /etc/apt/sources.list > /dev/null

RUN apt update; apt install -y zenoh

# Set the working directory inside the container
WORKDIR app/

# Install Python packages from requirements.txt
# Ensure requirements.txt is in the context directory during build
COPY src/requirements.txt .
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt
